language: erlang
git:
  submodules: false
install: true
before_script:
    - wget https://s3.amazonaws.com/rebar3/rebar3
    - chmod +x rebar3
script: ./rebar3 eunit
notifications:
  email: false
otp_release:
  - 18.2
  - 17.5
  - 17.0
